import fs from "fs";
import * as parser from "./parser.js";

const code = fs.readFileSync("uix/example.uix", "utf-8");
const tagMap = {
  App: "div",
  Title: "h1",
  Row: "div",
  Button: "button",
  Input: "input",
  Text: "span"
};

const ast = parser.parse(code);

// Tracking
const usedIdentifiers = new Set();
const boundVariables = new Set();
const stateDefaults = {};

function capitalize(str) {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : "";
}

function extractIdentifiers(value) {
  // Only treat as identifier if it's a valid JS expression (e.g., user.name)
  if (typeof value === "string" && /^[a-zA-Z_$][a-zA-Z0-9_$.]*$/.test(value)) {
    const parts = value.split(".");
    usedIdentifiers.add(parts[0]);
  }
}

function renderProps(props) {
  const safeProps = props || {};
  return Object.entries(safeProps)
    .map(([key, value]) => {
      if (typeof value === "object" && value.bind) {
        const varName = value.bind;
        const defaultVal = value.bindDefault ?? "";
        boundVariables.add(varName);
        stateDefaults[varName] = defaultVal;
        usedIdentifiers.add(`set${capitalize(varName)}`);
        return `value={${varName}} onChange={e => set${capitalize(varName)}(e.target.value)}`;
      }

      extractIdentifiers(value);

      if (key === "text") return null;
      if (key.startsWith("on")) return `${key}={${value}}`;

      return `${key}="${value}"`;
    })
    .filter(Boolean)
    .join(" ");
}

function generateJSX(node, indent = "  ") {
  const { type, props, children } = node;
  const childIndent = indent + "  ";

  if (type === "If") {
    extractIdentifiers(node.condition);
    const body = children.map(c => generateJSX(c, childIndent)).join("\n");
    return `${indent}{${node.condition} ? (\n${body}\n${indent}) : null}`;
  }

  if (type === "For") {
    extractIdentifiers(node.list);
    usedIdentifiers.add(node.item);
    const body = children.map(c => generateJSX(c, childIndent + "  ")).join("\n");
    return `${indent}{${node.list}.map((${node.item}) => (\n${childIndent}<React.Fragment key={${node.item}.id || JSON.stringify(${node.item})}>\n${body}\n${childIndent}</React.Fragment>\n${indent}))}`;
  }

  const jsxTag = tagMap[type] || type;
  const propStr = renderProps(props);

  let innerText = null;
  if (props?.text) {
    if (typeof props.text === "string" && !/^[a-zA-Z_$][a-zA-Z0-9_$.]*$/.test(props.text)) {
      innerText = `{${JSON.stringify(props.text)}}`; // Treat as literal string
    } else {
      extractIdentifiers(props.text);
      innerText = `{${props.text}}`;
    }
  }

  const inner = [
    innerText,
    ...(children || []).map(c => generateJSX(c, childIndent))
  ].filter(Boolean).join("\n");

  return `${indent}<${jsxTag}${propStr ? " " + propStr : ""}>\n${inner}\n${indent}</${jsxTag}>`;
}

// Generate JSX body
const jsxBody = ast.map(node => generateJSX(node)).join("\n");

// Destructure props & auto-state
const allUsed = new Set([...usedIdentifiers, ...boundVariables]);
const propsToInject = Array.from(allUsed).filter(id => !boundVariables.has(id) && !id.startsWith("set")).sort();

const autoStates = Array.from(boundVariables)
  .map(varName => `  const [${varName}, set${capitalize(varName)}] = React.useState(${JSON.stringify(stateDefaults[varName] ?? "")});`)
  .join("\n");

const propDestructure = propsToInject.join(", ");

const output = `// Auto-generated by UIX compiler
import React from "react";

export default function CompiledUI({ ${propDestructure} }) {
${autoStates ? autoStates + "\n" : ""}
  return (
    <>
${jsxBody}
    </>
  );
}
`;

fs.writeFileSync("src/CompiledUI.jsx", output);
console.log("✅ Compiled with props:", propDestructure || "(none)");
if (autoStates) {
  console.log("✅ Injected state for:", Array.from(boundVariables).join(", "));
}
