// Auto-generated by UIX compiler
import React from "react";

export default function CompiledUI({ name, setName, greet, users, showMore, toggle }) {
  return (
    <>
      <div>
        <h1>User List</h1>
        {users.map((user) => (
          <React.Fragment key={user.id || JSON.stringify(user)}>
            <div>
              <p>{user.name}</p>
            </div>
          </React.Fragment>
        ))}
        {showMore ? (
          <button onClick={toggle}>Show More</button>
        ) : null}
      </div>
    </>
  );
}
