// Auto-generated by UIX compiler
import React from "react";

export default function CompiledUI({ Greet, greet, name, showMore, toggle, user, users }) {

  return (
    <>
  <div>
    <h1>
{"User List"}
    </h1>
    {users.map((user) => (
      <React.Fragment key={user.id || JSON.stringify(user)}>
        <div>
          <span>
{user.name}
          </span>
        </div>
      </React.Fragment>
    ))}
    <input bind="name">

    </input>
    <button onClick={greet}>
{Greet}
    </button>
    {showMore ? (
      <button onClick={toggle}>
{"Show More"}
      </button>
    ) : null}
  </div>
    </>
  );
}
